"""create all table

Revision ID: 4f488a60d197
Revises:
Create Date: 2022-11-23 14:51:55.498091

"""
from alembic import op
import sqlalchemy as sa


import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '4f488a60d197'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=55), nullable=True),
    sa.Column('last_name', sa.String(length=55), nullable=True),
    sa.Column('profile_img', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    op.create_table('pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('destination_link', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=55), nullable=False),
    sa.Column('about', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE pins SET SCHEMA {SCHEMA};")
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.String(length=55), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE boards SET SCHEMA {SCHEMA};")
    op.create_table('board_pins',
    sa.Column('pins_id', sa.Integer(), nullable=False),
    sa.Column('boards_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boards_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['pins_id'], ['pins.id'], ),
    sa.PrimaryKeyConstraint('pins_id', 'boards_id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE board_pins SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_pins')
    op.drop_table('boards')
    op.drop_table('pins')
    op.drop_table('users')
    # ### end Alembic commands ###
